# Generated by Django 4.0.3 on 2024-07-21 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pybo', '0003_answer_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='board',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
